name: TDX News Auto Crawler

on:
  # 手动触发
  workflow_dispatch:
  # 定时触发：每15分钟运行一次
  schedule:
    - cron: '*/15 * * * *'
  # 推送代码时也运行（可选）
  push:
    branches: [ main, master ]

jobs:
  crawl-news:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run news crawler
      run: |
        python github_crawler.py
        
    - name: Commit and push if changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add tdx_all_news.db tdx_all_news_export.csv
        git commit -m "Auto update: News data $(date +'%Y-%m-%d %H:%M:%S')" || exit 0
        git pull --rebase origin main
        git push
        
    - name: Upload database as artifact
      uses: actions/upload-artifact@v4
      with:
        name: news-database
        path: |
          tdx_all_news.db
          tdx_all_news_export.csv
        retention-days: 7